### ISSUE TITLE
[BUG] Crash when resizing during plays

### ISSUE THREAD

**Issue by AlexV525** [peacefulprogram/ddys#6]
```console
09-25 10:17:40.091  2568  2568 D AndroidRuntime: Shutting down VM
09-25 10:17:40.091  2568  2568 E AndroidRuntime: FATAL EXCEPTION: main
09-25 10:17:40.091  2568  2568 E AndroidRuntime: Process: com.jing.ddys, PID: 2568
09-25 10:17:40.091  2568  2568 E AndroidRuntime: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class F.u0
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4953)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readParcelableInternal(Parcel.java:4807)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:4567)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:4347)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readListInternal(Parcel.java:5329)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readArrayListInternal(Parcel.java:5348)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:4597)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:4347)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel$LazyValue.apply(Parcel.java:4445)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel$LazyValue.apply(Parcel.java:4404)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.BaseBundle.getValue(BaseBundle.java:374)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.BaseBundle.getValue(BaseBundle.java:357)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.BaseBundle.getValue(BaseBundle.java:350)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Bundle.getParcelableArrayList(Bundle.java:1046)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.e0.a(SourceFile:247)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.A1.a(SourceFile:36)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.A1.Z(SourceFile:17)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at N.f.Z(SourceFile:54)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at F.w.a(SourceFile:1)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.A1.a(SourceFile:189)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.A1.Z(SourceFile:29)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at N.f.Z(SourceFile:54)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at F.w.Y(SourceFile:1)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at F.v.D(SourceFile:136)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at F.v.u(SourceFile:1)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at F.B.o(SourceFile:21)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at F.P0.a(SourceFile:42)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at F.B.f(SourceFile:11)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.c0.e(SourceFile:114)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeView.I0(SourceFile:1)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.WrappedComposition.f(SourceFile:1)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.WrappedComposition.g(SourceFile:1)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.lifecycle.w.a(SourceFile:23)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.lifecycle.x.a(SourceFile:111)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.c0.e(SourceFile:76)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:114)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.View.dispatchAttachedToWindow(View.java:21308)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2879)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2350)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9194)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:832)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7884)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-25 10:17:40.091  2568  2568 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: CREATOR
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at java.lang.Class.getField(Class.java:1635)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4930)
09-25 10:17:40.091  2568  2568 E AndroidRuntime:        ... 59 more
09-25 10:17:40.092   334  1323 W ActivityTaskManager:   Force finishing activity com.jing.ddys/.main.MainActivity
```

**Comment by peacefulprogram** [comment]
Can't reproduce this Exception,but found another
